### ISSUE TITLE
1.18.2 version

### ISSUE THREAD

**Issue by Emberfire** [MadaHaz/SleepingServerStopperMod-Forge#6]
Hi, sorry for bothering you.

Could this plugin be made to work with 1.18.2? I tried modifying it myself but I'm getting an error for invalid plugin.yml (even without editing anything).

Here's the stack trace:
`
[ERROR]: Could not load 'plugins\sleepingserverstoppermod-3.0.0-1.20.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
`

**Comment by MadaHaz** [comment]
@Emberfire My bad for the late response, got logged out of my GitHub account on mobile and missed the notification about this issue.
I've made a compatible version for 1.18.2, I haven't really tested it yet, but it should work properly and will upload the jar file soon.

From you stack trace, are you running this mod on a forge server? It isn't meant to be used for bukkit or spigot.
This mod is a port of a spigot version, you can see the link in the README of this mod. That mod might have links to a bukkit version.
